### ISSUE TITLE
Error when "&" and fmt_markdown(columns=TRUE)

### ISSUE THREAD

**Issue by xavidp** [GSK-Biostatistics/gto#4]
Hi:

First of all, thanks for sharing this useful feature added to gt & officeverse that was needed.

I've noticed my first issue with some combination of params in Rmd code. I managed to reproduce my issue in a simple example, which seems to be related to including the character ampersand ("&") in a character column and using fmt_markdown(columns = TRUE) (which I needed in my code, in my real use case)

Reprex:
```
#load officer and gt
library(officer)
library(gt)
library(gto)
library(tibble)
data <- head(exibble) %>% 
  add_case(char="foo & bar")

gt_tbl <- data %>% 
  gt() %>%
  fmt_markdown(columns = TRUE)

  
## Create docx and add gt table
doc <- read_docx()
doc <- body_add_gt(doc, value = gt_tbl)
```

Error triggered:
```
Error in read_xml.raw(charToRaw(enc2utf8(x)), "UTF-8", ..., as_html = as_html,  : 
  xmlParseEntityRef: no name [68]
```

Using R 4.2.2, gt 0.8.0, gtp 0.1.0, officer 0.6.1, xml2 1.3.3 (in case it matters)

Best,

**Comment by thebioengineer** [comment]
Hi @xavidp - thanks for the issue and using {gto}! 

Support for markdown columns in gt word outputs came in the latest gt 0.9.0 release. I was able to run your example and have it return the document with gt 0.9.0, officer 0.6.1.

If you could update gt to the latest CRAN release and run your code to see if you still get the same error, we can go from there.

**Comment by xavidp** [comment]
Awesome, thanks! I was not aware that the package evolved so much (great)!
I updated to the latest version (0.1.1), and issue vanished completely: thanks!
Best,
Xavier
