### ISSUE TITLE
The example code produces an error: SOLVED: CONFLICT WITH expss::gt

### ISSUE THREAD

**Issue by BorgeJorge** [GSK-Biostatistics/gto#5]
I'm trying to run the code from the documentation:
```
#load officer and gt
library(officer)
library(gt)
library(gto)

## create simple gt table
gt_tbl <- gt(head(exibble))

## Create docx and add gt table
doc <- read_docx()
doc <- body_add_gt(doc, value = gt_tbl)
```
And that last line produces the following error:
```
Error in body_add_gt(doc, value = gt_tbl) :  inherits(value, "gt_tbl") is not TRUE
```
If it helps, I notice that regardless of the flexttable object name, the error refers to "gt_tbl." For example:
```
> docc <- body_add_gt(docc, value = blah)
Error in body_add_gt(docc, value = blah) : inherits(value, "gt_tbl") is not TRUE
```

**Comment by BorgeJorge** [comment]
Ah, I discovered the problem: I also loaded the expss package, which has a gt function that masks gt's gt function, so once I specify gt::gt(), all is well.

Sorry about that!

**Comment by thebioengineer** [comment]
Closing since resolved by questioner.
